const config = {}

config.firstNames = [
    'Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Isabella', 'Sophia', 'Jackson', 'Lucas', 'Aiden',
    'Oliver', 'Ethan', 'Mia', 'Avery', 'Camila', 'Aria', 'Scarlett', 'Harper', 'Evelyn', 'Abigail',
    'Emily', 'Ella', 'Madison', 'Lily', 'Grace', 'Chloe', 'Nora', 'Zoe', 'Hannah', 'Lillian',
    'Layla', 'Mila', 'Riley', 'Penelope', 'Sofia', 'Ellie', 'Aubrey', 'Stella', 'Paisley', 'Hazel',
    'Luna', 'Lydia', 'Bella', 'Aurora', 'Savannah', 'Claire', 'Natalie', 'Kinsley', 'Brooklyn',
    'Leah', 'Zara', 'Audrey', 'Skylar', 'Aaliyah', 'Lucy', 'Ariana', 'Victoria', 'Liliana', 'Allison',
    'Sarah', 'Adeline', 'Gabriella', 'Alice', 'Mackenzie', 'Katherine', 'Lyla', 'Madelyn', 'Cora',
    'Ruby', 'Eleanor', 'Adalyn', 'Eliana', 'Violet', 'Everly', 'Sadie', 'Emery', 'Arianna', 'Peyton',
    'Gianna', 'Isabelle', 'Nova', 'Emilia', 'Hannah', 'Maya', 'Valentina', 'Willow', 'Naomi', 'Astrid',
    'Taylor', 'Lyric', 'Autumn', 'Piper', 'Lilith', 'Adriana', 'Athena', 'Ayla', 'Brielle'
  ]

  config.lastNames = [
    'Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor',
    'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson',
    'Clark', 'Rodriguez', 'Lewis', 'Lee', 'Walker', 'Hall', 'Allen', 'Young', 'Hernandez', 'King',
    'Wright', 'Lopez', 'Hill', 'Scott', 'Green', 'Adams', 'Baker', 'Gonzalez', 'Nelson', 'Carter',
    'Mitchell', 'Perez', 'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins',
    'Stewart', 'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy', 'Bailey',
    'Rivera', 'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Torres', 'Peterson', 'Gray', 'Ramirez',
    'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett', 'Wood', 'Barnes', 'Ross',
    'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson', 'Hughes', 'Flores', 'WA',
    'Butler', 'Simmons', 'Foster', 'Gonzales', 'Bryant', 'Alexander', 'Russell', 'Griffin', 'Diaz', 'Hayes'
  ]

  config.streetNames = [
    'Maple Street', 'Oak Avenue', 'Pine Lane', 'Cedar Drive', 'Elm Court', 'Willow Road', 'Birch Circle', 'Poplar Avenue', 'Sycamore Lane', 'Aspen Court',
    'Main Street', 'First Avenue', 'Second Street', 'Third Avenue', 'Fourth Street', 'Fifth Avenue', 'Sixth Street', 'Seventh Avenue', 'Eighth Street', 'Ninth Avenue',
    'Broadway', 'Park Place', 'Grove Street', 'Highland Avenue', 'Riverside Drive', 'Meadow Lane', 'Sunset Boulevard', 'Hillside Avenue', 'Crescent Drive', 'Valley View Road',
    'Greenwood Avenue', 'Rose Street', 'Lakeview Terrace', 'Forest Drive', 'Harbor Lane', 'Mountain View Drive', 'Sunnydale Avenue', 'Riverwalk Lane', 'Westminster Road', 'Lakeside Drive',
    'Chestnut Street', 'Beech Avenue', 'Cherry Lane', 'Hickory Court', 'Magnolia Road', 'Juniper Circle', 'Cypress Drive', 'Palm Avenue', 'Mulberry Lane', 'Fern Court',
    'Holly Street', 'Garden Avenue', 'Tulip Lane', 'Daisy Court', 'Sunflower Road', 'Lilac Circle', 'Azalea Drive', 'Violet Lane', 'Carnation Court', 'Rosemary Avenue',
    'Brookside Street', 'Alder Avenue', 'Wisteria Lane', 'Acorn Drive', 'Fountain View Road', 'Blossom Court', 'Cottonwood Circle', 'Bluebell Avenue', 'Primrose Lane', 'Mossy Oak Court',
    'Silver Birch Street', 'Goldenrod Avenue', 'Ivy Lane', 'Wildflower Drive', 'Peachtree Street', 'Sassafras Avenue', 'Pearl Lane', 'Emerald Court', 'Amber Avenue', 'Ruby Lane',
    'Cobblestone Street', 'Majestic Avenue', 'Quail Run Lane', 'Glenwood Terrace', 'Willowbrook Avenue', 'Winding Way', 'Trinity Court', 'Heritage Lane', 'Sunrise Avenue', 'Moonlight Drive',
    'Timber Lane', 'Eagle View Road', 'Harmony Street', 'Meadowlark Lane', 'Avalon Avenue', 'Whispering Pines Drive', 'Haven Court', 'Orchard Road', 'Silverado Avenue', 'Sparrow Lane',
    'Cactus Street', 'Desert View Road', 'Oasis Lane', 'Palm Tree Court', 'Sandstone Avenue', 'Sunset Ridge Drive', 'Mesa Circle', 'Rustic Lane', 'Sunny Mesa Road', 'Sierra Vista Avenue'
  ]

  config.address2 = ['','apt','','suite']

  config.citiesData = [
    { city: 'New York', state: 'NY', zip: '10001' },
    { city: 'Los Angeles', state: 'CA', zip: '90001' },
    { city: 'Chicago', state: 'IL', zip: '60601' },
    { city: 'Houston', state: 'TZ', zip: '77001' },
    { city: 'Phoenix', state: 'AZ', zip: '85001' },
    { city: 'Philadelphia', state: 'PA', zip: '19101' },
    { city: 'San Antonio', state: 'TX', zip: '78201' },
    { city: 'San Diego', state: 'CA', zip: '92101' },
    { city: 'Dallas', state: 'TX', zip: '75201' },
    { city: 'San Jose', state: 'CA', zip: '95101' },
    { city: 'Austin', state: 'TX', zip: '73301' },
    { city: 'Jacksonville', state: 'FL', zip: '32201' },
    { city: 'San Francisco', state: 'CA', zip: '94101' },
    { city: 'Indianapolis', state: 'IN', zip: '46201' },
    { city: 'Columbus', state: 'OH', zip: '43001' },
    { city: 'Fort Worth', state: 'TX', zip: '76101' },
    { city: 'Charlotte', state: 'NC', zip: '28201' },
    { city: 'Detroit', state: 'MI', zip: '48201' },
    { city: 'El Paso', state: 'TX', zip: '79901' },
    { city: 'Memphis', state: 'TN', zip: '38101' },
    { city: 'Seattle', state: 'WA', zip: '98101' },
    { city: 'Denver', state: 'CO', zip: '80201' },
    { city: 'Washington', state: 'DC', zip: '20001' },
    { city: 'Boston', state: 'MA', zip: '02101' },
    { city: 'Nashville', state: 'TN', zip: '37201' },
    { city: 'Baltimore', state: 'MD', zip: '21201' },
    { city: 'Oklahoma City', state: 'OK', zip: '73101' },
    { city: 'Louisville', state: 'KY', zip: '40201' },
    { city: 'Portland', state: 'OR', zip: '97201' },
    { city: 'Las Vegas', state: 'NV', zip: '89101' },
    { city: 'Milwaukee', state: 'WI', zip: '53201' },
    { city: 'Albuquerque', state: 'NM', zip: '87101' },
    { city: 'Tucson', state: 'AZ', zip: '85701' },
    { city: 'Fresno', state: 'CA', zip: '93650' },
    { city: 'Sacramento', state: 'CA', zip: '94203' },
    { city: 'Long Beach', state: 'CA', zip: '90801' },
    { city: 'Kansas City', state: 'MO', zip: '64101' },
    { city: 'Mesa', state: 'AZ', zip: '85201' },
    { city: 'Atlanta', state: 'GA', zip: '30301' },
    { city: 'VA Beach', state: 'VA', zip: '23450' },
    { city: 'Omaha', state: 'NE', zip: '68101' },
    { city: 'Colorado Springs', state: 'CO', zip: '80901' },
    { city: 'Raleigh', state: 'NC', zip: '27601' },
  ]

  config.productNames = [
    "QuantumByte Processor",
    "CyberLink ProVision Glasses",
    "NanoCharge Power Bank",
    "RoboGuard Security System",
    "HyperSync Wireless Charger",
    "QuantumGrip Gaming Mouse",
    "DigitalFlare VR Headset",
    "TechnoSwift Smartwatch",
    "AeroStream Drone",
    "PixelPulse Camera Drone",
    "HoloLink Augmented Reality Kit",
    "QuantumCore Quantum Computer",
    "SparkSync Bluetooth Earbuds",
    "EchoWave Noise-Canceling Headphones",
    "TurboFlash USB-C Flash Drive",
    "VaporEdge Gaming Console",
    "EchoPulse Smart Speaker",
    "QuantumScape VR Gloves",
    "NanoPods Miniature Speakers",
    "CyberMesh Wi-Fi Router",
    "NovaSync Cloud Storage",
    "GravityLens VR Camera",
    "PixelHarmony Digital Photo Frame",
    "BlazeStream Graphics Card",
    "SonicRift 3D Printer",
    "QuantumTouch Smartphone",
    "PulseBeam Fitness Tracker",
    "TechnoGlide Electric Scooter",
    "SolarFlare Solar Charger",
    "AeroGlide Hoverboard",
    "TurboFlow Laptop Cooling Pad",
    "QuantumFlow Quantum Sensor",
    "VisionQuest AR Glasses",
    "HoloCube 3D Display",
    "QuantumSpark Smart Mirror",
    "QuantumPod Charging Dock",
    "TechNova LED Desk Lamp",
    "PixelVista 360° Camera",
    "AeroLink Smart Home Hub",
    "QuantumVibe Electric Skateboard",
    "NanoDrive Portable SSD",
    "RoboTracker GPS Tracker",
    "EchoSync Smart Refrigerator",
    "QuantumWave Smart Thermostat",
    "AeroDrone Racing Kit",
    "QuantumArc Gaming Keyboard",
    "PixelSync 4K Monitor",
    "SolarGlide Portable Generator",
    "CyberFrame Digital Art Tablet",
    "QuantumPulse Heart Rate Monitor",
    "TurboVolt Electric Bike",
    "PixelPad Graphic Tablet",
    "SonicBlast Bluetooth Speaker",
    "QuantumFlex Foldable Phone",
    "TechHaven Home Automation Kit",
    "AeroStream Air Purifier",
    "QuantumTouch Digital Pen",
    "PulsePod Sleep Tracker",
    "HoloSync Meditation App",
    "EchoJet Wireless Charger",
    "SolarHarbor Solar-Powered Lamp",
    "QuantumBoost Portable Power Station",
    "PixelFlow Touchscreen Gloves",
    "AeroLink Home Security System",
    "QuantumMesh Smart Backpack",
    "NanoFlash Portable LED Light",
    "RoboPet AI-Powered Pet Companion",
    "EchoGlow Smart Light Bulb",
    "QuantumBlaze Racing Wheel",
    "PixelLink USB Hub",
    "TurboGrip Controller Grips",
    "SonicSync Bluetooth Keyboard",
    "AeroLume Smart LED Strip",
    "QuantumCraft DIY Electronics Kit",
    "HoloScape Virtual Landscape Projector",
    "PixelGlide Gaming Chair",
    "QuantumFrame Wireless Photo Printer",
    "SolarBeam Solar-Powered Charger",
    "EchoDrive Car Dash Cam",
    "QuantumRide Electric Scooter",
    "NanoGlow LED Makeup Mirror",
    "TechBlast Portable Bluetooth Printer",
    "PulseSync Health Monitoring System",
    "QuantumTouch Wireless Charging Pad",
    "AeroGlow RGB Mousepad",
    "PixelSync USB-C Hub",
    "SonicView VR Viewer",
    "HoloGrip Augmented Reality Gloves",
    "QuantumLink Smart Glasses",
    "NanoZoom Microscope Camera",
    "RoboHive Smart Beehive",
    "EchoScope Security Camera",
    "QuantumSphere Quantum-Resistant Encryption",
    "PixelSync Wireless Mouse",
    "TurboVision VR Headset",
    "QuantumWear Smart Clothing",
    "AeroCharge Solar Backpack",
    "SolarFlow Portable Fan",
    "EchoPlex Smart Home Display",
    "QuantumMind Brain-Computer Interface"
  ]

config.companyNames = [
  "AlphaTech Solutions",
  "BrightSky Innovations",
  "Crimson Enterprises",
  "DeltaForge Technologies",
  "EchoVision Industries",
  "FusionCorp",
  "Global Nexus Group",
  "Horizon Innovations",
  "Infinity Ventures",
  "Jupiter Dynamics",
  "Keystone Innovations",
  "Luminous Technologies",
  "Matrix Innovations",
  "NovaSphere Solutions",
  "Omega Systems",
  "Polaris Enterprises",
  "Quantum Solutions",
  "Redwood Technologies",
  "Solaris Innovations",
  "Titan Ventures",
  "Unity Dynamics",
  "Vortex Technologies",
  "Wavelength Systems",
  "Xenon Innovations",
  "YellowStone Enterprises",
  "Zephyr Solutions",
  "Aether Dynamics",
  "Borealis Technologies",
  "Cascade Innovations",
  "Dynamo Enterprises",
  "Eclipse Solutions",
  "Fahrenheit Ventures",
  "Galactic Innovations",
  "Helix Dynamics",
  "Inferno Technologies",
  "Jade Enterprises",
  "Kaleidoscope Innovations",
  "Lunar Systems",
  "Meridian Ventures",
  "Nebula Innovations",
  "Oasis Dynamics",
  "Phoenix Solutions",
  "Quasar Enterprises",
  "Radiant Innovations",
  "Spectrum Systems",
  "Terra Ventures",
  "Umbra Innovations",
  "Vista Dynamics",
  "Wavefront Technologies",
  "Xpress Enterprises",
  "Yonder Innovations",
  "Zenith Ventures",
  "Apex Innovations",
  "Bravo Technologies",
  "Catalyst Ventures",
  "Dynamix Innovations",
  "Enigma Enterprises",
  "Flare Dynamics",
  "Genesis Innovations",
  "Harmony Ventures",
  "Integra Technologies",
  "Jupiter Innovations",
  "Kairos Ventures",
  "Lunar Innovations",
  "Momentum Technologies",
  "Nucleus Ventures",
  "Orbit Innovations",
  "Pulse Dynamics",
  "Quantum Innovations",
  "Radiance Ventures",
  "Solar Innovations",
  "Terra Innovations",
  "Unity Innovations",
  "Vortex Innovations",
  "Wavelength Innovations",
  "Xenon Ventures",
  "Yonder Ventures",
  "Zenith Innovations",
  "Alpha Innovations",
  "BrightSky Technologies",
  "Crimson Ventures",
  "Delta Technologies",
  "EchoVision Ventures",
  "Fusion Innovations",
  "Global Nexus Technologies",
  "Horizon Ventures",
  "Infinity Technologies",
  "Jupiter Ventures",
  "Keystone Technologies",
  "Luminous Ventures",
  "Matrix Technologies",
  "NovaSphere Ventures",
  "Omega Technologies",
  "Polaris Ventures",
  "Quantum Technologies",
  "Redwood Ventures",
  "Solaris Ventures",
  "Titan Technologies"
];

config.easyPasswords = [
  'HappyDays','PassWord','EasyLife','HomeComing','BabyGirl','BabyBoy'
]

config.fakeEmails = [
  'example.email',
  'test.user',
  'demo',
  'placeholder',
  'fake.email',
  'temp.user',
  'sample.email',
  'user.test',
  'no.reply',
  'anonymous.email'
]

config.fakeDomains = [
  'fake-gmail.com','fake-yahoo.com','fake-hotmail.com','fake-icloud.com','fake-msn.com','fake-email.com','fake-ymail.com'
]



module.exports = config;